title: <p align="center" style="font-size:20px"> Alhousseynou BALL </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alhousseynou-ball/">LinkedIn</a> |
  <a href="https://github.com/ball-alhousseynou">GitHub</a>
  </p>
  
  <p align="justify">
  🌱 Hi, I'm working as a Data Scientist at La Javaness
  <br><br>
  👀 I'm interested in Machine Learning and NLP
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
